### ISSUE TITLE
DND task between different pane seems to add indent before the task

### ISSUE THREAD

**Issue by Quorafind** [artem-barmin/obsidian-block-drag-n-drop#1]
![image](https://user-images.githubusercontent.com/13215013/163512916-38a86407-fa49-48fd-a6f3-3d374ca96067.png)

**Comment by artem-barmin** [comment]
That's intended behaviour. I assume that item moved on another item should be added as child of target node.

**Comment by Quorafind** [comment]
![image](https://user-images.githubusercontent.com/13215013/163573798-d10d562a-5a17-4830-8ad9-1a15d9ae92fe.png)

But I dragged and dropped in under the normal text , it seems to be added as a child node ? Is it normal either?
