### ISSUE TITLE
Replace use of six dot handle with the builtin fold mark handle.

### ISSUE THREAD

**Issue by oblinger** [artem-barmin/obsidian-block-drag-n-drop#13]
I **LOVE** this plugin but found it hard to keep using since the six dot handles one each line are quite distracting for general usage.

I have no idea if the existing Obsidian source code allows easy extension of the drag and drop capability for the built-in folding marker used in obsidian.  My sense is this plugin will only achieve large scale usage once, the six dot handles are removed and the built-in folding handle is used instead.  (but of course I have no idea if this is even possible given the underlying code)

**Comment by ronrdev** [comment]
I hope all the outlining plugins can play well together and with core Obsidian. Make this optional or reveal on hover. I'm using the drag and drop plugin, and the zoom plugin to make Obsidian more like Logseq/Workflowy. 
This is how I got it to look so far. My use case is for outlining and writing fiction. I try to stay as distraction free as possible. For some reason the icons don't bother me. I have them at 20% opacity until hover.

https://user-images.githubusercontent.com/13022919/167232949-19bf7096-3117-41c9-b572-de909dc1fa25.mp4

https://user-images.githubusercontent.com/13022919/167233082-5c5be419-1460-42be-b217-d95b1497380e.mp4


Checkout Workflowy to see how three separate icons work together. 
https://www.youtube.com/watch?v=_5cofZwOsFY

**Comment by artem-barmin** [comment]
Thank you for supportive words! 

Regarding handler: that's actually usual way of showing drag-n-drop handle. See Notion example: 
<img width="492" alt="Screenshot 2022-05-07 at 22 05 45" src="https://user-images.githubusercontent.com/11332147/167268436-bae9e88b-3ba1-4f24-84b6-a1e794fc25e9.png">

You can use also CSS snippet from #5 to show drag handle only on hover, or wait until I will implement this as part of plugin itself

**Comment by oblinger** [comment]
Thanks!  yeah, show only on hover would really do the trick, especially if it did  not take up screen real-estate when not visible.

As far as the look, I was thinking about one-note... if I remember correctly you drag the bullet itself to the new place where you want the bullet to be.  I always found this to be quite intuitive.  you are just yanking the bullet mark itself around.  but anyway, having a marker that disappears is almost as good!  thanks!

**Comment by artem-barmin** [comment]
Duplicate #5
