### ISSUE TITLE
The plugin does not work for me

### ISSUE THREAD

**Issue by oscarcanoc** [artem-barmin/obsidian-block-drag-n-drop#19]
I don't know what I'm doing wrong but the option to move the lists doesn't appear I have the plugin activated but it doesn't work look
![Captura de pantalla (17)](https://user-images.githubusercontent.com/101314808/176501236-e40d8a9a-5ed7-408e-be1c-2b958ce559a0.png)

**Comment by artem-barmin** [comment]
Please write Obsidian version and list of other plugins

**Comment by artem-barmin** [comment]
List of installed community plugins. 

Also - have you activated drag-n-drop plugin?

**Comment by oscarcanoc** [comment]
![Captura de pantalla (18)](https://user-images.githubusercontent.com/101314808/176534697-adea53cb-512c-4bda-a2ea-d22c32e79437.png)

yes

**Comment by artem-barmin** [comment]
Can't reproduce
