### ISSUE TITLE
FR: reorder list items

### ISSUE THREAD

**Issue by imeed166** [artem-barmin/obsidian-block-drag-n-drop#6]
The ability to reorder list items as mentioned in this [issue](https://github.com/artem-barmin/obsidian-block-drag-n-drop/issues/2#issuecomment-1101491554).

**Comment by artem-barmin** [comment]
https://github.com/artem-barmin/obsidian-block-drag-n-drop/issues/2#issuecomment-1100092428 - video that demonstrate how position accordingly to target item change between two modes:
1. Just reorder
2. Move as subtree

**Comment by artem-barmin** [comment]
fixed with release 1.1.0
