### ISSUE TITLE
Bug: undo doesn't work until after clicking on text

### ISSUE THREAD

**Issue by imeed166** [artem-barmin/obsidian-block-drag-n-drop#7]
I have to select text before undoing the move. Is it possible to make it work right after moving without having to click on text ?

https://user-images.githubusercontent.com/38974541/163835664-d5142366-6e6e-4a59-a74b-07a111ec341f.mov

**Comment by artem-barmin** [comment]
Yes, that's easy. Will be available in next release

**Comment by artem-barmin** [comment]
Released 1.0.6, please check

**Comment by imeed166** [comment]
Done, thank you.
